# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        self.bot = QtWidgets.QWidget()
        self.bot.setObjectName("bot")
        self.label_3 = QtWidgets.QLabel(self.bot)
        self.label_3.setGeometry(QtCore.QRect(130, 80, 331, 71))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.bot)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 190, 511, 211))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 140, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(90, 40, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.bot)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.bot)
        self.link = QtWidgets.QWidget()
        self.link.setObjectName("link")
        self.label = QtWidgets.QLabel(self.link)
        self.label.setGeometry(QtCore.QRect(130, 80, 331, 71))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.link)
        self.groupBox.setGeometry(QtCore.QRect(40, 190, 511, 211))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(160, 140, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(80, 70, 341, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(216, 100, 79, 24))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.link)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.link)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DS Rich Presence"))
        self.label_3.setText(_translate("MainWindow", "Add the bot\'s FC to your friend list before continuing to the next page."))
        self.pushButton_2.setText(_translate("MainWindow", "Continue"))
        self.label_5.setText(_translate("MainWindow", "XXXX-XXXX-XXXX"))
        self.label_4.setText(_translate("MainWindow", "Link a Friend Code"))
        self.label.setText(_translate("MainWindow", "Make certain that you have added the bot account\'s FC to your friendlist before pressing \"Log In\"."))
        self.pushButton.setText(_translate("MainWindow", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your friend code here!"))
        self.label_2.setText(_translate("MainWindow", "Link a Friend Code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
