name: 'Build 3DS-RPC'
on:
  release:
    types: [published]

jobs:
  build:
    name: 'Build 3DS-RPC'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.10.11

    # Windows Build
    - name: "Build"
      if: matrix.os == 'windows-latest'
      run: cd client/scripts && ./build.bat

    - name: "Upload Build"
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: client/dist/3DS-RPC.exe

    # MacOS Build
    - name: "Build"
      if: matrix.os == 'macos-latest'
      run: |
        cd client/scripts &&
        ./build.sh &&
        cd ../dist &&
        zip -yr mac.zip 3DS-RPC.app/

    - name: "Upload Build"
      if: matrix.os == 'macos-latest'
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: client/dist/mac.zip
